services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - financial_postgres_data:/var/lib/postgresql/data

  slackbot:
    build: ./bot
    restart: always
    depends_on:
      - db
    environment:
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_APP_TOKEN=${SLACK_APP_TOKEN}
      - DB_HOST=db
      - DB_USER=${POSTGRES_USER}
      - DB_PASS=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
      - PYTHONUNBUFFERED=1  # <--- CRITICAL: Forces logs to write immediately
    volumes:
      - ./financial_downloads:/app/downloads  # Maps a folder on Pi to container for saving files
      - ./financial_logs:/app/logs # <--- Maps the log folder

  viewer:
    build: ./viewer
    restart: always
    depends_on:
      - db
    ports:
      - "8501:8501"  # <--- Allows access from your LAN
    environment:
      - DB_HOST=db
      - DB_USER=${POSTGRES_USER}
      - DB_PASS=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
      - OPENBLAS_CORETYPE=ARMV8
    volumes:
      - ./financial_downloads:/app/downloads # Read-Only access to files

volumes:
  financial_postgres_data: